import type { SeatLayout } from '../types/table';

/**
 * Built-in seat layouts matching Valence configurations.
 * For round tables, leftCount/rightCount/topCount/bottomCount are all 0
 * and seats are distributed evenly around the circumference.
 */
export const SEAT_LAYOUTS: SeatLayout[] = [
  {
    id: 'round-6',
    name: 'Round 6-Top',
    description: 'Round table with 6 seats',
    seatCount: 6,
    leftCount: 0,
    rightCount: 0,
    topCount: 0,
    bottomCount: 0,
    tableShape: 'round',
    isDefault: false,
  },
  {
    id: 'round-8',
    name: 'Round 8-Top',
    description: 'Round table with 8 seats',
    seatCount: 8,
    leftCount: 0,
    rightCount: 0,
    topCount: 0,
    bottomCount: 0,
    tableShape: 'round',
    isDefault: true,
  },
  {
    id: 'round-10',
    name: 'Round 10-Top',
    description: 'Round table with 10 seats',
    seatCount: 10,
    leftCount: 0,
    rightCount: 0,
    topCount: 0,
    bottomCount: 0,
    tableShape: 'round',
    isDefault: false,
  },
  {
    id: 'round-12',
    name: 'Round 12-Top',
    description: 'Round table with 12 seats',
    seatCount: 12,
    leftCount: 0,
    rightCount: 0,
    topCount: 0,
    bottomCount: 0,
    tableShape: 'round',
    isDefault: false,
  },
  {
    id: 'rect-6',
    name: 'Rectangle 6-Seat',
    description: 'Rectangular table with 6 seats',
    seatCount: 6,
    leftCount: 2,
    rightCount: 2,
    topCount: 1,
    bottomCount: 1,
    tableShape: 'rectangle',
    isDefault: false,
  },
  {
    id: 'rect-8',
    name: 'Rectangle 8-Seat',
    description: 'Rectangular table with 8 seats',
    seatCount: 8,
    leftCount: 3,
    rightCount: 3,
    topCount: 1,
    bottomCount: 1,
    tableShape: 'rectangle',
    isDefault: false,
  },
  {
    id: 'rect-10',
    name: 'Rectangle 10-Seat',
    description: 'Rectangular table with 10 seats',
    seatCount: 10,
    leftCount: 3,
    rightCount: 3,
    topCount: 2,
    bottomCount: 2,
    tableShape: 'rectangle',
    isDefault: false,
  },
  {
    id: 'rect-12',
    name: 'Rectangle 12-Seat',
    description: 'Rectangular table with 12 seats',
    seatCount: 12,
    leftCount: 4,
    rightCount: 4,
    topCount: 2,
    bottomCount: 2,
    tableShape: 'rectangle',
    isDefault: false,
  },
  {
    id: 'oval-8',
    name: 'Oval 8-Seat',
    description: 'Oval table with 8 seats',
    seatCount: 8,
    leftCount: 3,
    rightCount: 3,
    topCount: 1,
    bottomCount: 1,
    tableShape: 'oval',
    isDefault: false,
  },
  {
    id: 'oval-10',
    name: 'Oval 10-Seat',
    description: 'Oval table with 10 seats',
    seatCount: 10,
    leftCount: 4,
    rightCount: 4,
    topCount: 1,
    bottomCount: 1,
    tableShape: 'oval',
    isDefault: false,
  },
];

export function getSeatLayout(id: string): SeatLayout | undefined {
  return SEAT_LAYOUTS.find((l) => l.id === id);
}
